<?php
/*
 * 优惠券管理
 * */
namespace app\admin\controller;


use app\admin\model\Classify;
use app\admin\model\Coupon;
use app\admin\model\CouponGet;
use app\admin\model\CouponUse;
use think\Db;
use think\Exception;
use think\facade\Request;
use think\facade\Validate;


class Discount extends BaseUser
{
    //中间件
    protected $middleware = [
        'app\admin\middleware\Auth' => [
            //无须权限验证
            'except' => ['guide','uploadPic','_empty']
        ],
    ];


    protected $pid=6;
    protected $left_menus=[];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->assign('nav_path',Db::name('menus')->where('id',$this->pid)->value('link'));
        $left_menus=$this->getNav($this->pid);
        $this->left_menus=$left_menus;
        $this->assign("left_menus",$left_menus);

    }

    public function guide(){
        if(count($this->left_menus)){
            $menu=array_shift($this->left_menus);
            return redirect($menu['link']);
        }else{
            return view('public/guide');
        }

    }


    //列表
    public function coupon()
    {
        if(Request::isAjax()){
            $map=[];

            $listRow=input('limit');
            $title=input('title','');
            if(!empty(trim($title))){
                $map[]=['goods_name','like',"%{$title}%"];
            }

            //获取数据
            $data=Coupon::where($map)
                ->order('create_time desc')
                ->paginate($listRow);

            return json(['code'=>0,'msg'=>'','count'=>$data->total(),'data'=>$data->items()]);
        }else{

            $this->assign('nav_title','admin/discount/coupon');

            return view('coupon');
        }

    }

    //快捷修改
    public function changeField()
    {
        $id=input('post.id',0);
        $field = input("field","");
        $value = input("value","");
        try{
            if(!$id || $field=="" || $value==""){
                throw new Exception('无效参数');
            }
            $info=Coupon::get($id);
            if(!$info){
                throw new Exception('无效参数');
            }

            $info[$field] = $value;

            if($info->save()){
                $this->err['code']=0;
                $this->err['data']=$value;
                //添加日志
                $this->addLog(3,'修改优惠券【'.$info['coupon_name'].'】');
            }else{
                $this->err['msg']='网络延迟，稍后再试';
            }
        }catch (Exception $e){
            $this->err['msg']=$e->getMessage();
        }
        return json($this->err);
    }

    //编辑
    public function edit(){
        $id = input("id",0);
        if(Request::isAjax()){
            $data=input('post.');
            unset($data['id'],$data['images']);
            try{
                //验证规则
                $rule = [
                    'coupon_name'=>'require',
                ];
                if(!$id){

                    $rule['sale_money']='require';
                }
                $field = [
                    'coupon_name'=>'标题',
                    'sale_money'=>'优惠金额',
                ];
                $validate=Validate::make($rule,[],$field);
                if(!$validate->check($data)){
                    throw new Exception($validate->getError());
                }
                $type = 3;
                if($id){
                    $info = Coupon::get($id);
                    $old_cover = $info['cover'];
                    $data['update_time'] = time();
                    $res = $info->save($data);
                    if($res && !empty($old_cover) && $old_cover!=$data['cover']){
                        //删除原图片文件
                        @unlink('.'.$old_cover);
                    }
                }else{
                    //添加数据
                    $res=Coupon::create($data);
                    $type = 1;
                }

                if(!$res){
                    throw new Exception('网络延迟，稍后再试');
                }
                $this->err['code']=0;
                $this->err['msg']=($type==1?"添加":"修改")."优惠券【{$data['coupon_name']}成功！】";
                //添加日志
                $this->addLog($type,$this->err['msg']);
            }catch (Exception $e){
                $this->err['msg']=$e->getMessage();
            }

            return json($this->err);
        }else{
            if($id){
                $info = Coupon::get($id);
                if($info){
                    $this->assign('info',$info);
                }
            }
            //获取分类
            $classify = Classify::where('status',1)->where('parent_id',0)->order("sort","desc")->select();
            $this->assign('classify',$classify);

            $this->assign('nav_title','admin/discount/coupon');
            return view('coupon_edit');
        }
    }


    //手动发送优惠券
    public function sendCoupon(){
        if(Request::isAjax()){
            $data=input('post.');
            try{
                //验证规则
                $rule = [
                    'coupon_id'  => 'require',
                    'mobile'  => 'require',
                    'message'  => 'require',
                ];
                $field = [
                    'coupon_id'  => '优惠券',
                    'mobile'  => '手机',
                    'message'  => '备注',
                ];
                $validate=Validate::make($rule,[],$field);
                if(!$validate->check($data)){
                    throw new Exception($validate->getError());
                }
                //验证手机
                $uid=[];
                if(strtoupper($data['mobile'])!=="ALL"){
                    $uid[]=Db::name('member')
                        ->where('mobile',$data['mobile'])
                        ->value('member_id');
                }else{
                    $uid=Db::name('member')
                        ->where('status',1)
                        ->column('member_id');
                }
                if(!count($uid)){
                    throw new Exception('手机账号不存在');
                }
                $uid = array_unique($uid);//去重
                //发送优惠券
                $add_data=[];
                $t=time();
                $coupon=Db::name('coupon')->find($data['coupon_id']);
                if(!$coupon){
                    throw new Exception('无效的优惠券！');
                }
                $validity=$coupon['validity_time']?strtotime("+{$coupon['validity_time']} days"):0;
                foreach ($uid as $v){
                    $add_data[]=[
                        'coupon_id'=>$data['coupon_id'],
                        'member_id'=>$v,
                        'validity'=>$validity,
                        'des'=>$data['message'],
                        'create_time'=>$t,
                        'update_time'=>$t
                    ];
                }

                $rows=Db::name('coupon_get')->insertAll($add_data);

                //发送消息
                $msg_data=[
                    'content'=>$validity?$data['message']." 优惠券请在 {$coupon['validity_time']}天 内使用。":$data['message'],
                    'create_time'=>$t
                ];
                if(strtoupper($data['mobile'])!=="ALL"){
                    $msg_data['member_id']=$uid[0];
                }
                Db::name('message')->insert($msg_data);


                $this->err['code']=0;
                $this->err['msg']="发送优惠券【{$rows}】张";
                //添加日志
                $this->addLog(1,$this->err['msg']);
            }catch (Exception $e){
                $this->err['msg']=$e->getMessage();
            }

            return json($this->err);
        }else{
            //获取优惠券
            $coupons=Db::name('coupon')
                ->field('coupon_id,coupon_name')
                ->where('status',1)
                ->select();
            $this->assign('coupons',$coupons);

            $this->assign('nav_title','admin/discount/sendCoupon');

            return view('coupon_send');
        }

    }


    //获取记录
    public function gain(){
        if(Request::isAjax()){
            $map=[];
            $where=input('where',[]);
            if(!empty($where)){
                if(!empty($where['name'])){
                    $res=Db::name('member')->whereLike('nickname|mobile',"%{$where['name']}%")->column('member_id');
                    $map[]=count($res)?['member_id','in',$res]:['member_id','=',-1];
                }
                if(!empty($where['title'])){
                    $coupon_id = Db::name('coupon')->whereLike('coupon_name',"%{$where['title']}%")->column('coupon_id');
                    $map[]=count($coupon_id)?['coupon_id','in',$coupon_id]:['coupon_id','=',-1];
                }
            }
            $listRow=input('limit');
            $data=CouponGet::with(['coupon','member','employ'])->where($map)->order('create_time desc')->paginate($listRow);

            return json(['code'=>0,'msg'=>'','count'=>$data->total(),'data'=>$data->items()]);
        }else{

            $this->assign('nav_title','admin/discount/gain');
            return view('coupon_get');
        }
    }

    //使用记录
    public function employ(){
        if(Request::isAjax()){
            $map=[];
            $where=input('where',[]);
            if(!empty($where)){
                if(!empty($where['name'])){
                    $res=Db::name('member')->whereLike('nickname|mobile',"%{$where['name']}%")->column('member_id');
                    $map[]=count($res)?['member_id','in',$res]:['member_id','=',-1];
                }
                if(!empty($where['title'])){
                    $coupon_id = Db::name('coupon')->whereLike('coupon_name',"%{$where['title']}%")->column('coupon_id');
                    $map[]=count($coupon_id)?['coupon_id','in',$coupon_id]:['coupon_id','=',-1];
                }
            }
            $listRow=input('limit');
            $data=CouponUse::with(['coupon','member','gain','orders'])->where($map)->order('create_time desc')->paginate($listRow);

            return json(['code'=>0,'msg'=>'','count'=>$data->total(),'data'=>$data->items()]);
        }else{

            $this->assign('nav_title','admin/discount/employ');
            return view('coupon_use');
        }
    }

    //上传图片
    public function uploadPic(){
        //大小限制
        $size=config('image_upload_size');
        //类型限制
        $ext=config('image_upload_extension');

        $this->err = $this->uploadFiles('images','./uploads/coupon',$size,$ext);
        return json($this->err);
    }


    public function _empty()
    {
        //把所有城市的操作解析到city方法
        return view('public/404');
    }

}
