<?php
/*
 * 公共基础 控制器
 * */
namespace app\admin2\controller;

use app\model\Log;
use think\Controller;
use think\Db;
use think\facade\Request;


class BaseUser extends Controller
{
    //ajax返回值
    public $err=[
        'code'=>-1,
        'msg'=>'错误的请求',
    ];


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        //验证登录状态
        if(!session('?loginStatus') || !session('?user.uid')){
            if(Request::isAjax()){
                $this->err['msg']="抱歉您未登录，请刷新后重新登录";
                json($this->err)->send();exit;
            }else{
                redirect(url('/system'))->send();exit;
            }
        }

        //实时获得用户状态
        $res=Db::name('user')->field('session_id,status')->find(session('user.uid'));
        if(!$res){//获取失败，账号被注销
            session(null);
            if(Request::isAjax()){
                $this->err['msg']="抱歉您的账户已被注销，若有问题可联系管理员";
                json($this->err)->send();exit;
            }else{
                view("Public/406")->send();exit;
            }
        }

        //判断账号是否冻结
        if($res['status']==-1){
            session(null);
            if(Request::isAjax()){
                $this->err['msg']="抱歉您的账户已被冻结，若有问题可联系管理员";
                json($this->err)->send();exit;
            }else{
                view("Public/405")->send();exit;
            }
        }

        //处理重置密码
        if($res['session_id']=='resetPassword'){
            dump($res);exit;
            session(null);
            if(Request::isAjax()){
                $this->err['msg']="抱歉您的密码已重置，请重新登录";
                json($this->err)->send();exit;
            }else{
                echo '<script src="/static/admin/js/jquery-3.1.1.min.js" type="text/javascript"></script>
                <script src="/static/shop/libs/layer/layer.js" type="text/javascript"></script>
                <script>
                $(function() {
                 
                var url="/system.html";
                layer.alert("抱歉您的密码已重置，请重新登录",function() {
                   if(window.top==window.self){//不存在父页面
                    location.href=url;
                }else{
                    parent.location.href=url;
                }
                });
                 });
                </script>';
                exit;
            }
        }
        if(session_id()!=$res['session_id']){

            session(null);
            if(Request::isAjax()){
                $this->err['msg']="抱歉您的账户已在其他地点登录，若有问题可联系管理员";
                json($this->err)->send();exit;
            }else{
                echo '<script src="/static/admin/js/jquery-3.1.1.min.js" type="text/javascript"></script>
                    <script src="/static/shop/libs/layer/layer.js" type="text/javascript"></script>
                    <script>
                    $(function() {
                     
                    var url="/system.html";
                    layer.alert("抱歉您的账户已在其他地点登录，若有问题可联系管理员",function() {
                       if(window.top==window.self){//不存在父页面
                        location.href=url;
                    }else{
                        parent.location.href=url;
                    }
                    });
                     });
                    </script>';
                exit;
            }
        }
        /*//处理同步手机、姓名
        if($res['session_id']=='synchronization'){
            session(null);
            if(Request::isAjax()){
                $this->err['msg']="抱歉您的账号已重置，请重新登录";
                json($this->err)->send();exit;
            }else{
                echo '<script src="/static/admin/js/jquery-3.1.1.min.js" type="text/javascript"></script>
                <script src="/static/shop/libs/layer/layer.js" type="text/javascript"></script>
                <script>
                $(function() {
                 
                var url="/system.html";
                layer.alert("抱歉您的账号已重置，请重新登录",function() {
                   if(window.top==window.self){//不存在父页面
                    location.href=url;
                }else{
                    parent.location.href=url;
                }
                });
                 });
                </script>';
                exit;
            }
        }*/


        //遍历系统配置
        if(!session('?config')){
            $config=Db::name('config')->where('type',1)->column('value','varname');
            session('config',$config);
        }else{
            $config=session('config');
        }
        foreach($config as $key=>$val){
            $this->assign($key,$val);
        }
    }

    /*
     * 添加操作日志
     * type 0:请求或操作错误；1:增加；2:删除；3：修改；4：登录；5：退出
     *
     * */

    public function addLog($type,$msg,$status=1)
    {
        $data=[
            'type'=>$type,
            'msg'=>$msg,
            'status'=>$status,
        ];
        $log=new Log();
        $log->create($data);
    }

    //获取指定网站配置
    public function getSiteConfig($var_name){
        if(empty($var_name)){
            return false;
        }
        return Db::name('config')->where('varname',$var_name)->value('value');
    }


}
