<?php
/*
 * 首页 控制器
 * */
namespace app\shop\controller;


use app\model\Activity;
use app\model\GoodsShop;
use think\Controller;
use think\Db;
use think\Exception;
use think\facade\Request;
use think\facade\Session;

class Index extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->assign('nav_alias','home');

        //获取商城配置
        if(!session('?config')){
            $config=Db::name('config')->where('type',2)->column('value','varname');
            session('config',$config);
        }
        $this->assign('config',session('config'));
    }
    //商城首页
    public function index()
    {
        $nt=time();
        //获取活动
        $activity=Activity::field('id,goods_id,cover')
            ->where('status',1)
            ->where('isdelete',0)
            ->where('stop_time','>=',$nt)
            ->order('top desc,sort desc,create_time desc')
            ->limit(8)
            ->select();
        $this->assign('activity',$activity);

        //获取活动商品
        $goods_ids=Activity::where('status',1)
            ->where('stop_time','>=',$nt)
            ->where('isdelete',0)
            ->order('top desc,sort desc,create_time desc')
            ->limit(6)
            ->column('goods_id');
        if(!$goods_ids){
            $goods_ids=[0];
        }
        $activity_goods=GoodsShop::with('activity')
            ->field('id,goods_name,cover,price')
            ->whereIn('id',$goods_ids)
            ->where('status','=',1)
            ->where('is_int','=',0)
            ->where('is_new','=',0)
            ->where('inventory','>',0)
            ->where('is_delete','=',0)
            ->order('top desc,sort desc,create_time desc')
            ->select();
        $this->assign('activity_goods',$activity_goods);

        //dump($activity_goods);exit;
        //剔除活动商品id，查询热销商品
        $act_goods_ids=[];
        foreach ($activity_goods as $val){
            $act_goods_ids[]=$val['id'];
        }

        //获取热销商品
        $hot_goods=GoodsShop::field('id,goods_name,cover,price')
            ->where('status','=',1)
            ->where('is_int','=',0)
            ->where('is_new','=',0)
            ->where('id','not in',$act_goods_ids)
            ->where('inventory','>',0)
            ->where('is_delete','=',0)
            ->order('top desc,sort desc,create_time desc')
            ->limit(20)
            ->select();
        $this->assign('hot_goods',$hot_goods);



        return view('index');
    }



    public function _empty()
    {
        //把所有城市的操作解析到city方法
        return view('public/404');
    }

}
